//player reducer

export const SET_PLAYING = 'SET_PLAYING';
export const SET_SHUFFLE = 'SET_SHUFFLE';
export const SET_REPEAT = 'SET_REPEAT';
export const SET_DEVICE_ID = 'SET_DEVICE_ID';
export const SET_POSITION = 'SET_POSITION';
export const SET_CURRENT = 'SET_CURRENT';
export const SET_CURRENT_TILE_ID = 'SET_CURRENT_TILE_ID';
export const SET_NEXT_TRACK = 'SET_NEXT_TRACK';
export const SET_PREVIOUS_TRACKS = 'SET_PREVIOUS_TRACKS';
export const SET_MUTED = 'SET_MUTED';
export const SET_VC_LANG = 'SET_VC_LANG';
export const SET_MIN_TYPE = 'SET_MIN_TYPE';
export const SET_MAX_TYPE = 'SET_MAX_TYPE';
export const SET_ISLANDDOUBLE_TYPE = 'SET_ISLANDDOUBLE_TYPE';
export const SET_ISLAND_POS = 'SET_ISLAND_POS';
export const SET_ISLAND_SWIPE_LEFT = 'SET_ISLAND_SWIPE_LEFT';
export const SET_ISLAND_SWIPE_RIGHT = 'SET_ISLAND_SWIPE_RIGHT';
export const SET_SIDEBAR_TYPE = 'SET_SIDEBAR_TYPE';
export const SET_PLAYER_READY = 'SET_PLAYER_READY';
export const SET_THEME = 'SET_THEME';
export const SET_LYRICS = 'SET_LYRICS';
export const SET_FONT = 'SET_FONT';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_EXPIRES_IN = 'SET_EXPIRES_IN';
export const SET_PREMIUM = 'SET_PREMIUM';

//library reducer
export const SET_PLAYLIST = 'SET_PLAYLIST';
export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST';
export const NEW_RELEASES = 'NEW_RELEASES';
export const MY_TOP_TRACKS = 'MY_TOP_TRACKS';
export const SET_FEATURED_PLAYLIST = 'SET_FEATURED_PLAYLIST';
export const SET_BOLLYWOOD_HITS = 'SET_BOLLYWOOD_HITS';
export const SET_BOLLYWOOD_NEW = 'SET_BOLLYWOOD_NEW';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_MY_TOP_ARTISTS = 'SET_MY_TOP_ARTISTS';
export const SET_MY_ARTISTS_RECOMMENDATIONS = 'SET_MY_ARTISTS_RECOMMENDATIONS';
export const SET_ARTISTS = 'SET_ARTISTS';

//user reducer
export const SET_USER = 'SET_USER';
export const SET_MY_DEVICES = 'SET_MY_DEVICES';

//app reducer
export const SET_NOTIBAR = 'SET_NOTIBAR';
export const SET_NOTIBAR_TYPE = 'SET_NOTIBAR_TYPE';
export const SET_NOTIBAR_POS = 'SET_NOTIBAR_POS';
export const SET_HEADER_INVERT = 'SET_HEADER_INVERT';
export const SET_HEADER_HIDE = 'SET_HEADER_HIDE';
export const SET_HEADER_COLLAPSE = 'SET_HEADER_COLLAPSE';
export const SET_ALBUM_BG = 'SET_ALBUM_BG';
export const SET_TRACK_TO_ADD = 'SET_TRACK_TO_ADD';
export const SET_HOME_SLIDER_TYPE = 'SET_HOME_SLIDER_TYPE';
export const SET_HOME_SLIDER_DELAY = 'SET_HOME_SLIDER_DELAY';
export const SET_HOME_SLIDER_AUTOPLAY = 'SET_HOME_SLIDER_AUTOPLAY';
export const TOGGLE_ADD_TO_PLAYLIST = 'TOGGLE_ADD_TO_PLAYLIST';
export const TOGGLE_KEYBOARD = 'TOGGLE_KEYBOARD';
export const TOGGLE_QUEUE = 'TOGGLE_QUEUE';
export const TOGGLE_MY_DEVICES = 'TOGGLE_MY_DEVICES';
export const NEW_RELEASES_TILE = 'NEW_RELEASES_TILE';
export const SET_DARKMODE = 'SET_DARKMODE';
export const TOGGLE_COLOR_PALETTE = 'TOGGLE_COLOR_PALETTE';
export const TOGGLE_HANDEDNESS = 'TOGGLE_HANDEDNESS';
